/* ZAYTOONA Ω — Integrated Annual School System UI v1.0 */
'use strict';
(function(){
  const CATALOG='./zaytoona/kefayat/catalog.min.json';
  const STORE='zaytoona.annual.v1';
  const state={records:[]};
  const load=async()=>{try{const r=await fetch(CATALOG,{cache:'no-store'});const j=await r.json();state.records=Array.isArray(j.records)?j.records:[]}catch{state.records=[]}};
  const grades=[1,2,3,4];
  const ar=n=>String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[d]);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const getProgress=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return{}}};
  const saveProgress=p=>localStorage.setItem(STORE,JSON.stringify(p));
  function group(){const out={};for(const r of state.records){const g=String(r.grade??'');const s=String(r.subject??r.material??'');const k=g+'||'+s;(out[k]??=[]).push(r)}return out}
  function summary(){const p=getProgress();let mastered=0,active=0,support=0;for(const r of state.records){const x=p[r.id]?.state;if(x==='متقنة')mastered++;else if(x==='قيد التطور'||x==='قيد التعلم')active++;else if(x==='تحتاج دعمًا')support++}return{total:state.records.length,mastered,active,support,rate:state.records.length?Math.round(mastered/state.records.length*100):0}}
  function annualView(root){const groups=group(),s=summary();let cards='';for(const grade of grades){const subjects=Object.entries(groups).filter(([k])=>k.startsWith(String(grade)+'||'));const count=subjects.reduce((n,[,v])=>n+v.length,0);cards+=`<div class="card"><span class="kicker">الصف ${ar(grade)}</span><h2>${ar(count)} كفاية</h2><div>${subjects.map(([k,v])=>{const sub=k.split('||')[1]||'غير محدد';return`<button class="item annual-sub" data-g="${grade}" data-s="${esc(sub)}"><span><b>${esc(sub)}</b><small>${ar(v.length)} كفاية · خريطة تعلم سنوية</small></span><em class="pill">فتح</em></button>`}).join('')||'<div class="empty">لا توجد بيانات لهذا الصف.</div>'}</div></div>`}
    root.innerHTML=`<section class="hero"><span class="eyebrow">المنظومة السنوية</span><h1>خطة تعلم كاملة، لا قائمة كفايات.</h1><p>تُحوّل زيتونة الكفايات المطلوبة إلى خريطة سنوية، ثم إلى تعلم وممارسة وتقويم وإتقان وعلاج وإثراء.</p></section><div class="grid4"><div class="metric"><b>كل الكفايات</b><strong>${ar(s.total)}</strong></div><div class="metric"><b>متقنة</b><strong>${ar(s.mastered)}</strong></div><div class="metric"><b>تحتاج دعمًا</b><strong>${ar(s.support)}</strong></div><div class="metric"><b>نسبة الإتقان</b><strong>${ar(s.rate)}٪</strong></div></div><div class="grid4" style="grid-template-columns:repeat(2,1fr)">${cards}</div>`;
    root.querySelectorAll('.annual-sub').forEach(b=>b.onclick=()=>subjectView(root,b.dataset.g,b.dataset.s));
  }
  function subjectView(root,g,s){const items=state.records.filter(r=>String(r.grade??'')===String(g)&&String(r.subject??r.material??'')===s);const p=getProgress();root.innerHTML=`<section class="card"><button class="back" id="annualBack">← الخطة السنوية</button><span class="kicker">الصف ${ar(g)} · ${esc(s)}</span><h1>خريطة الكفايات السنوية</h1><p class="muted">${ar(items.length)} كفاية. كل كفاية تمر عبر تعلم → ممارسة → دليل → تقويم → إتقان.</p><div>${items.map((r,i)=>{const m=p[r.id]?.state||'لم تبدأ';return`<button class="item annual-comp" data-id="${esc(r.id)}"><span><b>${ar(i+1)}. ${esc(r.competency||r.text||r.learningOutcome||r.standard)}</b><small>${esc(r.domain||'')} · ${esc(r.learningOutcome||r.outcome||'')}</small></span><em class="pill">${esc(m)}</em></button>`}).join('')}</div></section>`;root.querySelector('#annualBack').onclick=()=>annualView(root);root.querySelectorAll('.annual-comp').forEach(b=>b.onclick=()=>competencyView(root,b.dataset.id));}
  function competencyView(root,id){const r=state.records.find(x=>String(x.id)===String(id));if(!r)return annualView(root);const p=getProgress(),m=p[id]?.state||'لم تبدأ';root.innerHTML=`<section class="card"><button class="back" id="annualBack">← العودة</button><span class="kicker">الصف ${ar(r.grade)} · ${esc(r.subject||r.material||'')}</span><h1>${esc(r.competency||r.text||r.learningOutcome||r.standard)}</h1><p>${esc(r.learningOutcome||r.outcome||r.standard||'')}</p><div class="mastery"><strong>الحالة الحالية: ${esc(m)}</strong><span>المسار: تعلم → ممارسة → دليل → تقويم</span></div><div class="scoregrid"><button class="scorebtn" data-score="0.4">أحتاج دعمًا</button><button class="scorebtn" data-score="0.7">قيد التطور</button><button class="scorebtn" data-score="1">متقنة</button></div><p class="muted">هذه النسخة تحفظ حكم الإتقان محليًا لتطوير المسار لاحقًا.</p></section>`;root.querySelector('#annualBack').onclick=()=>annualView(root);root.querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>{const q=getProgress();const score=Number(b.dataset.score);q[id]={state:score>=.8?'متقنة':score>0?'قيد التطور':'تحتاج دعمًا',score,updatedAt:new Date().toISOString()};saveProgress(q);competencyView(root,id)})}
  async function boot(){await load();if(typeof App==='undefined')return;const oldDraw=App.draw;App.draw=function(){if(this.view==='annual')return annualView(document.getElementById('content'));return oldDraw.call(this)};const oldRender=App.render;App.render=function(){oldRender.call(this);const nav=document.querySelector('.znav');if(nav&&!nav.querySelector('[data-view="annual"]')){const b=document.createElement('button');b.className='navbtn '+(this.view==='annual'?'active':'');b.dataset.view='annual';b.textContent='الخطة السنوية';b.onclick=()=>{this.view='annual';this.selected=null;this.query='';this.render()};nav.appendChild(b)}};App.render();}
  window.addEventListener('load',boot);
})();
