/* ZAYTOONA Ω — KEFAYAT SYNC v1.0 */
(function(global){'use strict';
 const BASE='https://raw.githubusercontent.com/smileeyes1/kefayat/main/raw_sources/';
 const STORE='zaytoona.kefayat.catalog.v1', META='zaytoona.kefayat.sync.v1';
 const SOURCES=[]; ['arabic','math','islamic','nurturing'].forEach(subject=>{for(let grade=1;grade<=4;grade++)SOURCES.push({subject,grade,file:`${subject}_grade_${grade}.txt`})});
 const clean=s=>String(s??'').replace(/\u00a0/g,' ').replace(/[\u200e\u200f]/g,'').replace(/\s+/g,' ').trim();
 const id=(g,s,n)=>`G${g}-${s.toUpperCase()}-${String(n).padStart(4,'0')}`;
 const subject=s=>s==='math'?'mathematics':s==='islamic'?'islamic_education':s;
 function parse(text,src){const out=[];for(const line0 of text.split(/\r?\n/)){const line=clean(line0);if(!line||line.startsWith('[TABLE')||!line.includes(' | '))continue;const c=line.split(' | ').map(clean);
   if(src.subject==='islamic'){if(c.length<6||['الكفايات الرئيسة','المجال'].includes(c[0]))continue;out.push({id:id(src.grade,'islamic_education',out.length+1),grade:src.grade,subject:'islamic_education',domain:null,main_competency:c[0]||null,sub_competency:c[1]||null,criterion:c[2]||null,learning_outcomes:[],mastery_levels:{'يتقن':c[3]||'','يطور':c[4]||'','يحاول':c[5]||''},values:[],provenance:{status:'USER-PROVIDED REFERENCE',source_id:src.file,location:`kefayat/raw_sources/${src.file}`,repository:'smileeyes1/kefayat',ref:'main'},source_text:line,normalized:null,source_row:c});continue}
   if(c.length<7||['المجال','المجال المعرفي'].includes(c[0])||['المعايير','المعيار'].includes(c[3]))continue;const hasOutcome=c.length>=8;out.push({id:id(src.grade,subject(src.subject),out.length+1),grade:src.grade,subject:subject(src.subject),domain:c[0]||null,main_competency:c[1]||null,sub_competency:c[2]||null,criterion:c[3]||null,learning_outcomes:hasOutcome&&c[4]?[c[4]]:[],mastery_levels:{'يتقن':c[hasOutcome?5:4]||'','يطور':c[hasOutcome?6:5]||'','يحاول':c[hasOutcome?7:6]||''},values:[],provenance:{status:'USER-PROVIDED REFERENCE',source_id:src.file,location:`kefayat/raw_sources/${src.file}`,repository:'smileeyes1/kefayat',ref:'main'},source_text:line,normalized:null,source_row:c});}return out}
 function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
 function save(records,meta){localStorage.setItem(STORE,JSON.stringify({schema_version:'kefayat-runtime-1.0',status:meta.status,records,coverage:meta.coverage,source_repository:'smileeyes1/kefayat',source_ref:'main',syncedAt:meta.syncedAt}));localStorage.setItem(META,JSON.stringify(meta))}
 async function sync(){const coverage=[],all=[];for(const src of SOURCES){try{const r=await fetch(BASE+src.file,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const rows=parse(await r.text(),src);all.push(...rows);coverage.push({...src,status:'PARSED',records:rows.length})}catch(e){coverage.push({...src,status:'ERROR',records:0,error:String(e.message||e)})}}
   const parsed=coverage.filter(x=>x.status==='PARSED').length, meta={status:parsed===SOURCES.length&&all.length?'SYNCED':'PARTIAL',sources:SOURCES.length,parsedSources:parsed,records:all.length,coverage,syncedAt:new Date().toISOString()};if(all.length)save(all,meta);global.ZaytoonaKefayatSync.records=all;global.ZaytoonaKefayatSync.meta=meta;return meta}
 const old=read(STORE);global.ZaytoonaKefayatSync={records:old?.records||[],meta:read(META),getRecords(){return this.records||[]},getMeta(){return this.meta},sync,ready:null};global.ZaytoonaKefayatSync.ready=sync().catch(()=>global.ZaytoonaKefayatSync.meta||{status:'ERROR'});
})(window);
