import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const src=fs.readFileSync(new URL('./learning-core.js',import.meta.url),'utf8');
const sandbox={localStorage:{_d:{},getItem(k){return this._d[k]??null},setItem(k,v){this._d[k]=String(v)}},window:null};
sandbox.window=sandbox;
vm.runInNewContext(src,sandbox);
const C=sandbox.ZLearningCore;
assert.equal(C.version,'1.0');
const plan=C.plan({state:'لم تبدأ',score:0},{competency:'قراءة كلمة',subject:'arabic',outcome:'يقرأ كلمة'});
assert.deepEqual(plan.sequence,['diagnose','teach','practice','check']);
const task=C.validateTask({competencyId:'a',prompt:'اختر',choices:['أ','ب'],correctIndex:1});
assert.equal(task.ok,true);
const db=C.submit({studentId:'s1',competencyId:'a',score:0.9,evidence:{type:'choice',value:'ب'}});
assert.equal(db.state,'قيد التطور');
const db2=C.submit({studentId:'s1',competencyId:'a',score:1,evidence:{type:'choice',value:'ب'}});
assert.equal(db2.state,'متقنة');
assert.equal(C.get({studentId:'s1',competencyId:'a'}).evidence.length,2);
console.log('learning core: PASS');
