/* ZAYTOONA Ω FACTORY v1.1 — dependency-aware, parallel-safe, resumable orchestration. */
(function(global){'use strict';
 const S=()=>global.ZaytoonaOmegaState;
 const registry=new Map();
 function register(def){if(!def||!def.id||typeof def.run!=='function')throw Error('invalid-job-definition');registry.set(def.id,def);}
 function validate(defs){const ids=new Set(defs.map(d=>d.id));for(const d of defs){if(!d.id)throw Error('job-id-required');for(const dep of(d.dependsOn||[]))if(!ids.has(dep))throw Error('missing-dependency:'+d.id+':'+dep);if((d.dependsOn||[]).includes(d.id))throw Error('self-dependency:'+d.id)}return true}
 function snapshot(defs){const saved=S().get().jobs||{};const all={};defs.forEach(d=>{const j=saved[d.id]||{};all[d.id]={id:d.id,title:d.title,status:j.status||'pending',dependsOn:d.dependsOn||[],attempts:j.attempts||0,result:j.result,error:j.error}});return all}
 async function run(def,ctx){const s=S();const old=s.get().jobs[def.id]||{};if(old.status==='done')return {ok:true,id:def.id,result:old.result,skipped:true};s.upsertJob({id:def.id,title:def.title,status:'running',attempts:(old.attempts||0)+1,dependsOn:def.dependsOn||[],error:null});s.event('job.started',{id:def.id,attempt:(old.attempts||0)+1});try{const result=await def.run(ctx);s.upsertJob({id:def.id,status:'done',result,error:null});s.event('job.done',{id:def.id});return {ok:true,id:def.id,result}}catch(error){const msg=error&&error.message||String(error);s.upsertJob({id:def.id,status:'failed',error:msg});s.event('job.failed',{id:def.id,error:msg});return {ok:false,id:def.id,error:msg}}}
 async function execute(defs,ctx){validate(defs);defs.forEach(register);let all=snapshot(defs);let remaining=new Set(defs.filter(d=>all[d.id].status!=='done').map(d=>d.id));let rounds=0;while(remaining.size&&rounds++<100){const runnable=[...remaining].map(id=>registry.get(id)).filter(d=>(d.dependsOn||[]).every(id=>all[id]&&all[id].status==='done'));if(!runnable.length){S().event('factory.blocked',{jobs:[...remaining],reason:'dependency-cycle-or-missing-dependency'});return {ok:false,blocked:[...remaining],reason:'dependency-cycle-or-missing-dependency',completed:Object.values(all).filter(x=>x.status==='done').map(x=>x.id)}}const results=await Promise.all(runnable.map(d=>run(d,ctx)));results.forEach(r=>{all[r.id]={...all[r.id],status:r.ok?'done':'failed',result:r.result,error:r.error};remaining.delete(r.id)});if(results.some(r=>!r.ok)){return {ok:false,failed:results.filter(r=>!r.ok),completed:Object.values(all).filter(x=>x.status==='done').map(x=>x.id)}}}return {ok:remaining.size===0,completed:Object.values(all).filter(x=>x.status==='done').map(x=>x.id)}}
 global.ZaytoonaOmegaFactory={register,execute,validate};
})(window);