import { mkdir, writeFile } from 'node:fs/promises';
import { loadState, saveState } from './store.mjs';
import { assertTransition, chooseReadyJob, recoverOrphanedJobs } from './state-machine.mjs';
import { appendEvent } from './state-journal.mjs';
import { persistEvent } from './persistence-worker.mjs';
const STATE=process.env.ZAYTOONA_STATE||'./.zaytoona/state.json';
const EVIDENCE=process.env.ZAYTOONA_EVIDENCE||'./.zaytoona/evidence.ndjson';
const HEARTBEAT_MS=Math.max(5000,Number(process.env.ZAYTOONA_HEARTBEAT_MS||30000));
const MAX_ATTEMPTS=Math.max(1,Number(process.env.ZAYTOONA_MAX_ATTEMPTS||3));
const LEASE_MS=Math.max(10000,Number(process.env.ZAYTOONA_LEASE_MS||120000));
const sleep=ms=>new Promise(r=>setTimeout(r,ms)); const worker=()=>process.env.ZAYTOONA_WORKER||`${process.pid}`;
async function evidence(e){await mkdir(new URL('.',`file://${process.cwd()}/.zaytoona/`),{recursive:true});await writeFile(EVIDENCE,JSON.stringify({...e,at:new Date().toISOString()})+'\n',{encoding:'utf8',flag:'a'});await appendEvent(e);await persistEvent(e).catch(()=>null)}
function live(j){return Boolean(j.lease?.expiresAt&&Date.parse(j.lease.expiresAt)>Date.now())}
function activeLeasedJob(jobs){return jobs.find(j=>['CLAIMED','RUNNING','VERIFYING','RECOVERING'].includes(j.status)&&live(j))??null}
async function claim(state,job){const w=worker();if(live(job)&&job.lease.worker!==w)return null;job.status=assertTransition(job.status,'CLAIMED');const fence=`${w}:${Date.now()}:${Math.random().toString(36).slice(2)}`;job.lease={worker:w,fence,acquiredAt:new Date().toISOString(),expiresAt:new Date(Date.now()+LEASE_MS).toISOString()};await saveState(STATE,state);await evidence({type:'CLAIMED',jobId:job.id,worker:w,fence});return fence}
export async function runOnce(executor){if(typeof executor!=='function')return{status:'BLOCKED',reason:'NO_EXECUTOR_CONFIGURED'};let state=await loadState(STATE);recoverOrphanedJobs(state.jobs);await saveState(STATE,state);const job=chooseReadyJob(state.jobs);if(!job){const active=activeLeasedJob(state.jobs);return active?{status:'BUSY',jobId:active.id}:{status:'IDLE'}}const fence=await claim(state,job);if(!fence)return{status:'BUSY',jobId:job.id};try{job.status=assertTransition(job.status,'RUNNING');job.attempts=(job.attempts||0)+1;await saveState(STATE,state);await evidence({type:'RUNNING',jobId:job.id,attempts:job.attempts});const result=await executor({...job,fence});state=await loadState(STATE);const current=state.jobs.find(j=>j.id===job.id);if(!current||current.lease?.fence!==fence)throw new Error('LEASE_FENCED');current.status=assertTransition(current.status,'VERIFYING');current.evidence=result;if(!result?.ok)throw new Error('EXECUTOR_RETURNED_NON_OK');current.status=assertTransition(current.status,'PASSED');current.lease=null;await saveState(STATE,state);await evidence({type:'PASSED',jobId:current.id,evidence:result});return{status:'PASSED',jobId:current.id}}catch(error){state=await loadState(STATE);const current=state.jobs.find(j=>j.id===job.id);if(!current)return{status:'BLOCKED',reason:'JOB_DISAPPEARED'};current.error=String(error?.message||error);if(['RUNNING','VERIFYING'].includes(current.status))current.status=assertTransition(current.status,'FAILED');current.status=assertTransition(current.status,'RECOVERING');if((current.attempts||0)>=MAX_ATTEMPTS)current.status=assertTransition(current.status,'BLOCKED');else current.status=assertTransition(current.status,'READY');current.lease=null;await saveState(STATE,state);await evidence({type:'RECOVERY',jobId:current.id,error:current.error,attempts:current.attempts,nextStatus:current.status});return{status:current.status,jobId:current.id,error:current.error,attempts:current.attempts}}}
export async function start(executor){let stopped=false;const stop=()=>{stopped=true};process.on('SIGTERM',stop);process.on('SIGINT',stop);while(!stopped){await runOnce(executor).catch(async e=>evidence({type:'RUNTIME_ERROR',error:String(e?.message||e)}));if(!stopped)await sleep(HEARTBEAT_MS)}}
if(import.meta.url===`file://${process.argv[1]}`)start();
