import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const SOURCES=[['arabic','GEM_KB_ARABIC_GRADES_1-4.md'],['math','GEM_KB_MATH_GRADES_1-4.md'],['islamic','GEM_KB_ISLAMIC_GRADES_1-4.md'],['nurturing','GEM_KB_NURTURING_GRADES_1-4.md']];
const BASE='https://raw.githubusercontent.com/smileeyes1/kefayat/main/';const LOCAL=process.env.KEFAYAT_LOCAL_DIR||'';const OUT='zaytoona/kefayat';
const clean=s=>String(s??'').replace(/\r/g,'').trim();const hash=s=>createHash('sha256').update(s).digest('hex');
const GRADE={'١':1,'٢':2,'٣':3,'٤':4,'1':1,'2':2,'3':3,'4':4,'الأول':1,'الثاني':2,'الثالث':3,'الرابع':4};
const gradeFrom=s=>{const m=s.match(/(?:^|##\s*)الصف\s*(١|٢|٣|٤|1|2|3|4|الأول|الثاني|الثالث|الرابع)\s*$/);return m?GRADE[m[1]]:null};
function isHeader(c){return c.some(x=>/المجال المعرفي|المجالات|المجال|كفايات الممارسة الرئيسة|الكفايات الرئيسة|الكفايات الفرعية|الكفاية الفرعية|المعايير التفصيلية|المعايير|نتاجات التعلم|مؤشرات الأداء|المؤشرات|يتقن/.test(x));}
function parse(source,text){const out=[];let grade=null,headers=null;for(const raw of text.split('\n')){const line=clean(raw);const detected=gradeFrom(line);if(detected){grade=detected;headers=null;continue}if(grade===null||!line.includes('|')||line.startsWith('[TABLE'))continue;const cells=line.split('|').map(clean);if(cells.length<4)continue;if(isHeader(cells)){headers=cells;continue}if(!headers||cells.length!==headers.length)continue;const r={id:`KF-${hash(`${source}|${grade}|${line}`).slice(0,16)}`,source,grade,raw:line};headers.forEach((h,i)=>{if(h)r[h]=cells[i]});r.competency=r['الكفايات الفرعية المستقلة بنيوياً']||r['الكفايات الفرعية']||r['الكفاية الفرعية']||'';r.standard=r['المعايير التفصيلية']||r['المعايير']||r['المعيار']||'';r.learningOutcome=r['نتاجات التعلم']||r['مؤشرات الأداء']||r['المؤشر']||'';r.mastery=r['يتقن']||'';r.developing=r['يطور']||r['يتطور']||'';r.attempting=r['يحاول']||'';out.push(r)}return out}
async function sourceText(file){if(LOCAL)return readFile(`${LOCAL}/${file}`,'utf8');const res=await fetch(BASE+file);if(!res.ok)throw Error(`SOURCE_FETCH_FAILED:${file}:${res.status}`);return res.text()}
const all=[],sources=[];for(const [source,file] of SOURCES){const text=await sourceText(file);const rows=parse(source,text);if(!rows.length)throw Error(`SOURCE_PARSED_EMPTY:${file}`);sources.push({source,file,sha256:hash(text),records:rows.length,mode:LOCAL?'BUILT_FROM_KEFAYAT_DOCX':'REMOTE_KB'});all.push(...rows)}
const unique=new Map();for(const r of all){const key=hash(`${r.source}|${r.grade}|${r.competency}|${r.standard}|${r.learningOutcome}`);if(!unique.has(key))unique.set(key,{...r,semanticKey:key})}const rows=[...unique.values()];const matrix={};for(const g of [1,2,3,4])for(const [s] of SOURCES)matrix[`${g}|${s}`]=rows.filter(r=>r.grade===g&&r.source===s).length;const missing=Object.entries(matrix).filter(([,n])=>n===0).map(([k])=>k);if(!rows.length||missing.length)throw Error(`CATALOG_INVALID:${missing.join(',')}`);
const catalog={schemaVersion:6,generatedAt:new Date().toISOString(),source:{repository:'smileeyes1/kefayat',branch:'main',baseUrl:BASE,buildStrategy:LOCAL?'Kefayat DOCX → build_gem_kb.py → Zaytoona parser':'Kefayat published KB',policy:'USER-PROVIDED REFERENCE; NOT OFFICIAL-VERIFIED'},recordCount:rows.length,sources,coverage:{grades:[1,2,3,4],subjects:SOURCES.map(([s])=>s),matrix},deduplication:{inputRecords:all.length,outputRecords:rows.length,removed:all.length-rows.length},records:rows};await mkdir(OUT,{recursive:true});await writeFile(`${OUT}/catalog.json`,JSON.stringify(catalog,null,2)+'\n');await writeFile(`${OUT}/catalog.min.json`,JSON.stringify(catalog)+'\n');await writeFile(`${OUT}/sync-manifest.json`,JSON.stringify({status:'PASS',recordCount:rows.length,sources,coverage:catalog.coverage,deduplication:catalog.deduplication},null,2)+'\n');console.log(JSON.stringify({status:'PASS',recordCount:rows.length,coverage:matrix,deduplication:catalog.deduplication}));
