import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import vm from 'node:vm';
const read=p=>readFile(p,'utf8');
const catalog=JSON.parse(await read('zaytoona/kefayat/catalog.json'));
assert.ok(catalog.recordCount>0,'CATALOG_EMPTY');
assert.equal(catalog.records.length,catalog.recordCount,'CATALOG_COUNT_MISMATCH');
const store=new Map();
function makeEnv(){const localStorage={setItem:(k,v)=>store.set(k,String(v)),getItem:k=>store.get(k)??null,removeItem:k=>store.delete(k)};const el=()=>({innerHTML:'',textContent:'',value:'',dataset:{},children:[],onclick:null,appendChild(x){this.children.push(x)},insertAdjacentHTML(){},querySelector(){return el()},querySelectorAll(){return []}});const document={body:el(),createElement:()=>el(),getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]};const c={console,localStorage,document,crypto:{randomUUID:()=>`e2e-${Math.random()}`},setTimeout,clearTimeout,Promise,Math,Date,structuredClone,fetch:async()=>({ok:true,json:async()=>catalog})};c.window=c;vm.createContext(c);return c}
const load=async(c,p)=>vm.runInContext(await read(p),c,{filename:p});
const c=makeEnv();await load(c,'zaytoona/annual-learning-engine-v1.js');await c.ZaytoonaAnnualLearning.load();const plan=c.ZaytoonaAnnualLearning.plan();assert.ok(plan.length>0,'ANNUAL_NO_COMPETENCY');const competency=plan[0];assert.ok(competency.id&&competency.grade>=1&&competency.grade<=4,'BAD_COMPETENCY');assert.ok(competency.week>=1&&competency.week<=36,'BAD_ANNUAL_PLACEMENT');
await load(c,'zaytoona/smart-lesson-generator-v1.js');const lesson=c.ZaytoonaSmartLesson.build(competency);assert.equal(lesson.competencyId,competency.id,'LESSON_COMPETENCY_MISMATCH');assert.equal(lesson.grade,competency.grade,'LESSON_GRADE_MISMATCH');assert.equal(lesson.duration,45,'LESSON_DURATION_INVALID');assert.ok(lesson.stages.length>=6,'LESSON_STAGES_INCOMPLETE');
await load(c,'zaytoona/assessment-engine-v1.js');const assessment=c.ZaytoonaAssessment.assess(lesson,100,0.8);assert.equal(assessment.competencyId,competency.id,'ASSESSMENT_COMPETENCY_MISMATCH');assert.equal(assessment.mastered,true,'MASTERY_NOT_RECORDED');c.ZaytoonaAnnualLearning.setState(competency.id,{status:'متقنة',stageIndex:0,week:competency.week});assert.equal(c.ZaytoonaAnnualLearning.state(competency.id).status,'متقنة','STATE_SAVE_FAILED');
const recovered=makeEnv();await load(recovered,'zaytoona/annual-learning-engine-v1.js');await load(recovered,'zaytoona/assessment-engine-v1.js');assert.equal(recovered.ZaytoonaAnnualLearning.state(competency.id).status,'متقنة','STATE_RECOVERY_FAILED');assert.equal(recovered.ZaytoonaAssessment.get(competency.id).mastered,true,'ASSESSMENT_RECOVERY_FAILED');assert.ok(recovered.ZaytoonaAnnualLearning.plan().some(r=>r.id===competency.id),'CATALOG_RECOVERY_FAILED');
console.log(JSON.stringify({status:'PASS',scenario:'Kefayat→annual→lesson→assessment→mastery→save→recovery→verify',competency:{id:competency.id,grade:competency.grade,subject:competency.subject,week:competency.week},lesson:{id:lesson.id,duration:lesson.duration,stages:lesson.stages.length},assessment:{score:assessment.score,mastered:assessment.mastered},recovery:{state:'متقنة',assessmentRecovered:true}},null,2));
